import { Pipe, PipeTransform } from '@angular/core';

export function Pad(n) {
	if (typeof n !== 'number') return '';
	if (n < 10) return '0' + n;
	return '' + n;
}

export function IsEmpty(obj: any): boolean {
	if (obj == null) return true;
	if (typeof obj === 'number') return false;
	return Object.keys(obj).length === 0;
}

@Pipe({ name: 'filter' })
export class FilterArrayPipe implements PipeTransform {
	transform(arr, fn): any[] {
		if (!Array.isArray(arr)) return [];
		if (typeof fn !== 'function') {
			console.error('must pass a function');
			return [];
		}
		return arr.filter(fn);
	}
}

export function FilterByProps(kw: string | null, it: Object, ...props: string[]): boolean {
	if (!kw || !it) return true;
	kw = kw.toLowerCase();
	return props.some(k => {
		const v = it[k];
		if (!v) return false;
		return v.toLowerCase().indexOf(kw) > -1;
	});
}

export function SortBy(...props: string[]): (a, b) => number {
	return (a, b): number => {
		let ret = 0;
		props.some(k => {
			let sortOrder = 1;
			if (k[0] === '-') {
				sortOrder = -1;
				k = k.substr(1);
			}
			const av = a[k], bv = b[k];
			if (av == null || av < bv) {
				ret = -1 * sortOrder;
			} else if (bv == null || av > bv) {
				ret = 1 * sortOrder;
			}
			return ret !== 0;
		});
		return ret;
	};
}

export function Throttle(callback: (...args: any[]) => any, thisArg: Object, limit: number = 100) {
	let wait = false;
	return function () {
		if (wait) return;
		wait = true;
		setTimeout(() => wait = false, limit);
		return Reflect.apply(callback, thisArg, arguments);
	};
}

// used https://github.com/substack/provinces/blob/master/provinces.json for state names

export const Countries = {
	ad: 'Andorra',
	ae: 'United Arab Emirates',
	af: 'Afghanistan',
	ag: 'Antigua And Barbuda',
	ai: 'Anguilla',
	al: 'Albania',
	am: 'Armenia',
	ao: 'Angola',
	aq: 'Antarctica',
	ar: 'Argentina',
	as: 'American Samoa',
	at: 'Austria',
	au: 'Australia',
	aw: 'Aruba',
	ax: 'Aland Islands',
	az: 'Azerbaijan',
	ba: 'Bosnia And Herzegovina',
	bb: 'Barbados',
	bd: 'Bangladesh',
	be: 'Belgium',
	bf: 'Burkina Faso',
	bg: 'Bulgaria',
	bh: 'Bahrain',
	bi: 'Burundi',
	bj: 'Benin',
	bl: 'Saint-Barthelemy',
	bm: 'Bermuda',
	bn: 'Brunei Darussalam',
	bo: 'Bolivia, Plurinational State Of',
	bq: 'Bonaire, Sint Eustatius And Saba',
	br: 'Brazil',
	bs: 'Bahamas',
	bt: 'Bhutan',
	bv: 'Bouvet Island',
	bw: 'Botswana',
	by: 'Belarus',
	bz: 'Belize',
	ca: 'Canada',
	cc: 'Cocos (Keeling) Islands',
	cd: 'Congo, The Democratic Republic Of The',
	cf: 'Central African Republic',
	cg: 'Congo',
	ch: 'Switzerland',
	ci: 'Cote Divoire',
	ck: 'Cook Islands',
	cl: 'Chile',
	cm: 'Cameroon',
	cn: 'China',
	co: 'Colombia',
	cr: 'Costa Rica',
	cu: 'Cuba',
	cv: 'Cape Verde',
	cw: 'Curacao',
	cx: 'Christmas Island',
	cy: 'Cyprus',
	cz: 'Czech Republic',
	de: 'Germany',
	dj: 'Djibouti',
	dk: 'Denmark',
	dm: 'Dominica',
	do: 'Dominican Republic',
	dz: 'Algeria',
	ec: 'Ecuador',
	ee: 'Estonia',
	eg: 'Egypt',
	eh: 'Western Sahara',
	er: 'Eritrea',
	es: 'Spain',
	et: 'Ethiopia',
	fi: 'Finland',
	fj: 'Fiji',
	fk: 'Falkland Islands (Malvinas)',
	fm: 'Micronesia, Federated States Of',
	fo: 'Faroe Islands',
	fr: 'France',
	ga: 'Gabon',
	gb: 'United Kingdom',
	gd: 'Grenada',
	ge: 'Georgia',
	gf: 'French Guiana',
	gg: 'Guernsey',
	gh: 'Ghana',
	gi: 'Gibraltar',
	gl: 'Greenland',
	gm: 'Gambia',
	gn: 'Guinea',
	gp: 'Guadeloupe',
	gq: 'Equatorial Guinea',
	gr: 'Greece',
	gs: 'South Georgia And The South Sandwich Islands',
	gt: 'Guatemala',
	gu: 'Guam',
	gw: 'Guinea-Bissau',
	gy: 'Guyana',
	hk: 'Hong Kong',
	hm: 'Heard Island And Mcdonald Islands',
	hn: 'Honduras',
	hr: 'Croatia',
	ht: 'Haiti',
	hu: 'Hungary',
	id: 'Indonesia',
	ie: 'Ireland',
	il: 'Israel',
	im: 'Isle Of Man',
	in: 'India',
	io: 'British Indian Ocean Territory',
	iq: 'Iraq',
	ir: 'Iran, Islamic Republic Of',
	is: 'Iceland',
	it: 'Italy',
	je: 'Jersey',
	jm: 'Jamaica',
	jo: 'Jordan',
	jp: 'Japan',
	ke: 'Kenya',
	kg: 'Kyrgyzstan',
	kh: 'Cambodia',
	ki: 'Kiribati',
	km: 'Comoros',
	kn: 'Saint Kitts And Nevis',
	kp: 'Korea',
	kr: 'Korea, Republic Of',
	kw: 'Kuwait',
	ky: 'Cayman Islands',
	kz: 'Kazakhstan',
	la: 'Lao Peoples Democratic Republic',
	lb: 'Lebanon',
	lc: 'Saint Lucia',
	li: 'Liechtenstein',
	lk: 'Sri Lanka',
	lr: 'Liberia',
	ls: 'Lesotho',
	lt: 'Lithuania',
	lu: 'Luxembourg',
	lv: 'Latvia',
	ly: 'Libya',
	ma: 'Morocco',
	mc: 'Monaco',
	md: 'Moldova, Republic Of',
	me: 'Montenegro',
	mf: 'Saint Martin (French Part)',
	mg: 'Madagascar',
	mh: 'Marshall Islands',
	mk: 'Macedonia, The Former Yugoslav Republic Of',
	ml: 'Mali',
	mm: 'Myanmar',
	mn: 'Mongolia',
	mo: 'Macao',
	mp: 'Northern Mariana Islands',
	mq: 'Martinique',
	mr: 'Mauritania',
	ms: 'Montserrat',
	mt: 'Malta',
	mu: 'Mauritius',
	mv: 'Maldives',
	mw: 'Malawi',
	mx: 'Mexico',
	my: 'Malaysia',
	mz: 'Mozambique',
	na: 'Namibia',
	nc: 'New Caledonia',
	ne: 'Niger',
	nf: 'Norfolk Island',
	ng: 'Nigeria',
	ni: 'Nicaragua',
	nl: 'Netherlands',
	no: 'Norway',
	np: 'Nepal',
	nr: 'Nauru',
	nu: 'Niue',
	nz: 'New Zealand',
	om: 'Oman',
	pa: 'Panama',
	pe: 'Peru',
	pf: 'French Polynesia',
	pg: 'Papua New Guinea',
	ph: 'Philippines',
	pk: 'Pakistan',
	pl: 'Poland',
	pm: 'Saint Pierre And Miquelon',
	pn: 'Pitcairn',
	pr: 'Puerto Rico',
	ps: 'Palestine, State Of',
	pt: 'Portugal',
	pw: 'Palau',
	py: 'Paraguay',
	qa: 'Qatar',
	re: 'Reunion',
	ro: 'Romania',
	rs: 'Serbia',
	ru: 'Russian Federation',
	rw: 'Rwanda',
	sa: 'Saudi Arabia',
	sb: 'Solomon Islands',
	sc: 'Seychelles',
	sd: 'Sudan',
	se: 'Sweden',
	sg: 'Singapore',
	sh: 'Saint Helena, Ascension And Tristan Da Cunha',
	si: 'Slovenia',
	sj: 'Svalbard And Jan Mayen',
	sk: 'Slovakia',
	sl: 'Sierra Leone',
	sm: 'San Marino',
	sn: 'Senegal',
	so: 'Somalia',
	sr: 'Suriname',
	ss: 'South Sudan',
	st: 'Sao Tome And Principe',
	sv: 'El Salvador',
	sx: 'Sint Maarten (Dutch Part)',
	sy: 'Syrian Arab Republic',
	sz: 'Swaziland',
	tc: 'Turks And Caicos Islands',
	td: 'Chad',
	tf: 'French Southern Territories',
	tg: 'Togo',
	th: 'Thailand',
	tj: 'Tajikistan',
	tk: 'Tokelau',
	tl: 'Timor-Leste',
	tm: 'Turkmenistan',
	tn: 'Tunisia',
	to: 'Tonga',
	tr: 'Turkey',
	tt: 'Trinidad And Tobago',
	tv: 'Tuvalu',
	tw: 'Taiwan, Province Of China',
	tz: 'Tanzania, United Republic Of',
	ua: 'Ukraine',
	ug: 'Uganda',
	um: 'United States Minor Outlying Islands',
	us: 'United States',
	uy: 'Uruguay',
	uz: 'Uzbekistan',
	va: 'Holy See (Vatican City State)',
	vc: 'Saint Vincent And The Grenadines',
	ve: 'Venezuela, Bolivarian Republic Of',
	vg: 'Virgin Islands, British',
	vi: 'Virgin Islands, U.S.',
	vn: 'Viet Nam',
	vu: 'Vanuatu',
	wf: 'Wallis And Futuna',
	ws: 'Samoa',
	ye: 'Yemen',
	yt: 'Mayotte',
	za: 'South Africa',
	zm: 'Zambia',
	zw: 'Zimbabwe',
};

export const CountriesList = Object.keys(Countries).map(function(k) { return { abbr: k, name: Countries[k] }; });

export const States = {
	'us': {
		al: 'Alabama',
		ak: 'Alaska',
		as: 'American Samoa',
		az: 'Arizona',
		ar: 'Arkansas',
		ca: 'California',
		co: 'Colorado',
		ct: 'Connecticut',
		de: 'Delaware',
		dc: 'District Of Columbia',
		fm: 'Federated States Of Micronesia',
		fl: 'Florida',
		ga: 'Georgia',
		gu: 'Guam',
		hi: 'Hawaii',
		id: 'Idaho',
		il: 'Illinois',
		in: 'Indiana',
		ia: 'Iowa',
		ks: 'Kansas',
		ky: 'Kentucky',
		la: 'Louisiana',
		me: 'Maine',
		mh: 'Marshall Islands',
		md: 'Maryland',
		ma: 'Massachusetts',
		mi: 'Michigan',
		mn: 'Minnesota',
		ms: 'Mississippi',
		mo: 'Missouri',
		mt: 'Montana',
		ne: 'Nebraska',
		nv: 'Nevada',
		nh: 'New Hampshire',
		nj: 'New Jersey',
		nm: 'New Mexico',
		ny: 'New York',
		nc: 'North Carolina',
		nd: 'North Dakota',
		mp: 'Northern Mariana Islands',
		oh: 'Ohio',
		ok: 'Oklahoma',
		or: 'Oregon',
		pw: 'Palau',
		pa: 'Pennsylvania',
		pr: 'Puerto Rico',
		ri: 'Rhode Island',
		sc: 'South Carolina',
		sd: 'South Dakota',
		tn: 'Tennessee',
		tx: 'Texas',
		ut: 'Utah',
		vt: 'Vermont',
		vi: 'Virgin Islands',
		va: 'Virginia',
		wa: 'Washington',
		wv: 'West Virginia',
		wi: 'Wisconsin',
		wy: 'Wyoming',
	},
	'ca': {
		ab: 'Alberta',
		bc: 'British Columbia',
		mb: 'Manitoba',
		nb: 'New Brunswick',
		nl: 'Newfoundland and Labrador',
		ns: 'Nova Scotia',
		nu: 'Nunavut',
		nt: 'Northwest Territories',
		on: 'Ontario',
		pe: 'Prince Edward Island',
		qc: 'Quebec',
		sk: 'Saskatchewan',
		yt: 'Yukon',
	},
};
